### ISSUE TITLE
[Feat] Header

### ISSUE THREAD

**Issue by yeoniii20** [AriAri-Dong/AriAri_Frontend#2]
# Todo 🚕
> Settings and Components
 
### Settings ⚙️

- [x] Add tailwind custom colors and styles
- [x] Change paths in tsconfig
- [x] Adding Fonts and Global Settings
- [x] Add Icon

### Components 🍄

- [x] Create Header Component
- [x] Create Small Button Component
- [x] Create Search Input Component
- [x] Create Tab Component
- [x] Create Tooltip Component
- [x] Create Dropdown Component
- [x] Create Notification Component
- [x] Create User Component

### etc 🚀

- [x] Using context
- [x] Setting up file structure
- [x] Creating page folders
